set local check_function_bodies = off;

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "service_role";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "service_role";

create table "public"."budget" (
  "created_at"   timestamp with time zone not null default now(),
  "amount"       numeric                  not null,
  "category_id"  uuid                     not null,
  "user_id"      uuid                     not null,
  "id"           uuid                     not null default gen_random_uuid(),
  "updated_at"   timestamp with time zone not null default now(),
  "period_start" date                     not null default now(),
  "period_end"   date                     not null,
  constraint "budget_pkey" primary key (id)
);

alter table "public"."budget"
  enable row level security;

create table "public"."category" (
  "name"    text not null,
  "user_id" uuid not null,
  "id"      uuid not null default gen_random_uuid(),
  "type"    text default 'expense'::text,
  "color"   text default '#ef4444'::text,
  "icon"    text default '💰'::text,
  constraint "category_pkey" primary key (id)
);

alter table "public"."category"
  enable row level security;

create table "public"."currency" (
  "id"        bigint generated by default as identity not null,
  "code"      text   not null,
  "unit_text" text   not null,
  constraint "currency_id_key" unique (id),
  constraint "currency_pkey" primary key (id)
);

alter table "public"."currency"
  enable row level security;

create table "public"."transaction" (
  "id"               uuid                     not null default gen_random_uuid(),
  "created_at"       timestamp with time zone not null default now(),
  "type"             text                     not null,
  "description"      text,
  "category_id"      uuid,
  "amount"           real                     not null,
  "transaction_date" timestamp with time zone not null default now(),
  "user_id"          uuid                     not null,
  "currency_id"      bigint                   not null default '1'::bigint,
  constraint "Transaction_pkey" primary key (id)
);

alter table "public"."transaction"
  enable row level security;

create table "public"."user" (
  "id"                    uuid                     not null default gen_random_uuid(),
  "created_at"            timestamp with time zone not null default now(),
  "updated_at"            timestamp with time zone not null default now(),
  "username"              text                     not null,
  "preferred_currency_id" bigint                   default '1'::bigint,
  constraint "user_pkey" primary key (id)
);

create or replace function public.handle_new_user()
  returns trigger
  language plpgsql
  security definer
  AS $function$
begin
  insert into public.user (id, username)
  values (
    new.id,
    new.raw_user_meta_data->>'username'
  );

  return new;
end;
$function$;

alter table "public"."budget"
  add constraint "budget_category_id_fkey" foreign key (category_id) references public.category(id) on update cascade on delete cascade;

alter table "public"."transaction"
  add constraint "transaction_category_id_fkey" foreign key (category_id) references public.category(id) on update cascade on delete set default;

alter table "public"."transaction"
  add constraint "transaction_currency_id_fkey" foreign key (currency_id) references public.currency(id) on update cascade on delete set default;

alter table "public"."budget"
  add constraint "budget_user_id_fkey" foreign key (user_id) references public."user"(id) on update cascade on delete cascade;

alter table "public"."category"
  add constraint "category_user_id_fkey" foreign key (user_id) references public."user"(id) on update cascade on delete cascade;

alter table "public"."transaction"
  add constraint "transaction_user_id_fkey" foreign key (user_id) references public."user"(id) on update cascade on delete cascade;

alter table "public"."user"
  add constraint "user_preferred_currency_id_fkey" foreign key (preferred_currency_id) references public.currency(id) on update cascade on delete set default;

create view "public"."budget_summary" with (security_invoker=on) AS  SELECT b.id AS budget_id,
    b.user_id,
    c.name AS category,
    c.color AS category_color,
    c.icon AS category_icon,
    b.amount AS budget,
    COALESCE(sum(t.amount), (0)::real) AS spent,
    ((b.amount)::double precision - COALESCE(sum(t.amount), (0)::real)) AS remaining,
    round((((COALESCE(sum(t.amount), (0)::real) / (NULLIF(b.amount, (0)::numeric))::double precision) * (100)::double precision))::numeric, 2) AS used_percent
   FROM ((public.budget b
     JOIN public.category c ON ((c.id = b.category_id)))
     LEFT JOIN public.transaction t ON (((t.category_id = b.category_id) AND (t.transaction_date >= b.period_start) AND (t.transaction_date < (b.period_end + '1 day'::interval)))))
  GROUP BY b.id, c.name, c.color, c.icon;

create view "public"."user_balance" with (security_invoker=on) AS  SELECT user_id,
    COALESCE(sum(
        CASE
            WHEN (type = 'income'::text) THEN amount
            ELSE (- amount)
        END), (0)::real) AS balance
   FROM public.transaction
  GROUP BY user_id;

create index idx_transaction_category_date on public.transaction using btree (category_id, transaction_date);

create index idx_transaction_user on public.transaction using btree (user_id);

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

create policy "Enable delete for users based on user_id" on "public"."budget"
  for delete
  to PUBLIC
  using ((( select auth.uid() as uid) = user_id));

create policy "Enable insert for authenticated users only" on "public"."budget"
  for insert
  to "authenticated"
  with check (true);

create policy "Enable to update users own data" on "public"."budget"
  for update
  to PUBLIC
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "Enable users to view their own data only" on "public"."budget"
  for select
  to "authenticated"
  using ((( select auth.uid() as uid) = user_id));

create policy "Enable delete for users based on user_id" on "public"."category"
  for delete
  to PUBLIC
  using ((( select auth.uid() as uid) = user_id));

create policy "Enable insert for authenticated users only" on "public"."category"
  for insert
  to "authenticated"
  with check (true);

create policy "Enable users to view their own data only" on "public"."category"
  for select
  to "authenticated"
  using ((( select auth.uid() as uid) = user_id));

create policy "Policy with table joins" on "public"."category"
  for update
  to PUBLIC
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "Enable read access for all users" on "public"."currency"
  for select
  to PUBLIC
  using (true);

create policy "Enable delete for users based on user_id" on "public"."transaction"
  for delete
  to PUBLIC
  using ((( select auth.uid() as uid) = user_id));

create policy "Enable insert for authenticated users only" on "public"."transaction"
  for insert
  to "authenticated"
  with check (true);

create policy "Enable users to view their own data only" on "public"."transaction"
  for select
  to "authenticated"
  using ((( select auth.uid() as uid) = user_id));

create policy "Policy with table joins" on "public"."transaction"
  for update
  to PUBLIC
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "Enable insert for users based on user_id" on "public"."user"
  for insert
  to PUBLIC
  with check (false);

create policy "Enable read access for all users" on "public"."user"
  for select
  to PUBLIC
  using (true);

grant execute on function "public"."handle_new_user"() to public, "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."budget" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."category" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."currency" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."transaction" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."user" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."budget_summary" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."user_balance" to "anon", "authenticated", "postgres", "service_role";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "anon";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "authenticated";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "service_role";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "anon";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "authenticated";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "service_role";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "anon";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "authenticated";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "service_role";

